// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: RemoteControl.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace RemoteControlGrpcService {
  /// <summary>
  /// The greeting service definition.
  /// </summary>
  public static partial class RemoteController
  {
    static readonly string __ServiceName = "remoteController.RemoteController";

    static readonly grpc::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_google_protobuf_Empty = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Empty.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::RemoteControlGrpcService.CommandReply> __Marshaller_remoteController_CommandReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::RemoteControlGrpcService.CommandReply.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::RemoteControlGrpcService.Pong> __Marshaller_remoteController_Pong = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::RemoteControlGrpcService.Pong.Parser.ParseFrom);

    static readonly grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::RemoteControlGrpcService.CommandReply> __Method_GetInstructions = new grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::RemoteControlGrpcService.CommandReply>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "GetInstructions",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_remoteController_CommandReply);

    static readonly grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::RemoteControlGrpcService.Pong> __Method_Ping = new grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::RemoteControlGrpcService.Pong>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Ping",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_remoteController_Pong);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::RemoteControlGrpcService.RemoteControlReflection.Descriptor.Services[0]; }
    }

    /// <summary>Client for RemoteController</summary>
    public partial class RemoteControllerClient : grpc::ClientBase<RemoteControllerClient>
    {
      /// <summary>Creates a new client for RemoteController</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public RemoteControllerClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for RemoteController that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public RemoteControllerClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected RemoteControllerClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected RemoteControllerClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      /// Sends a greeting
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncServerStreamingCall<global::RemoteControlGrpcService.CommandReply> GetInstructions(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetInstructions(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Sends a greeting
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncServerStreamingCall<global::RemoteControlGrpcService.CommandReply> GetInstructions(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_GetInstructions, null, options, request);
      }
      public virtual global::RemoteControlGrpcService.Pong Ping(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Ping(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::RemoteControlGrpcService.Pong Ping(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Ping, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::RemoteControlGrpcService.Pong> PingAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return PingAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::RemoteControlGrpcService.Pong> PingAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Ping, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override RemoteControllerClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new RemoteControllerClient(configuration);
      }
    }

  }
}
#endregion
